# Generated by Django 6.1 on 2026-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the professor', max_length=255, verbose_name='Professor Name')),
                ('university', models.CharField(help_text='Institution or university name', max_length=255, verbose_name='University')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Country')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Department / Lab')),
                ('contact_group', models.CharField(blank=True, db_index=True, help_text='Categorization tag (e.g., AI/ML Group, Systems, Fall 2026 Batch)', max_length=150, verbose_name='Contact Group')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Professor Email')),
                ('email_subject', models.CharField(blank=True, help_text='Customized email subject line for outreach', max_length=255, verbose_name='Email Subject')),
                ('profile_url', models.TextField(blank=True, help_text='Faculty page or personal homepage URL', verbose_name='Professor Profile URL')),
                ('lab_website_url', models.TextField(blank=True, help_text='Research laboratory or department portal URL', verbose_name='Lab / University Website URL')),
                ('research_area', models.TextField(blank=True, help_text='Core research fields, topics, and keywords', verbose_name='Research Area')),
                ('recent_publications', models.TextField(blank=True, help_text='Selected recent papers or conference proceedings', verbose_name='Recent Publications')),
                ('h_index', models.IntegerField(blank=True, null=True, verbose_name='h-index')),
                ('citations', models.IntegerField(blank=True, null=True, verbose_name='Citations')),
                ('funding_status', models.CharField(blank=True, help_text='e.g. Fully Funded, RA/TA Available, Self-funded', max_length=150, verbose_name='Funding Status')),
                ('pipeline_status', models.CharField(choices=[('identified', 'Identified / Backlog'), ('researched', 'Researched / Qualified'), ('email_drafted', 'Email Drafted'), ('contacted', 'First Contact Sent'), ('follow_up_1', 'Follow-up #1 Sent'), ('follow_up_2', 'Follow-up #2 Sent'), ('discussion', 'In Discussion / Replied'), ('meeting_scheduled', 'Meeting Scheduled'), ('interviewed', 'Interviewed'), ('applied', 'Application Submitted'), ('accepted', 'Accepted / Offer'), ('declined', 'Declined / Closed'), ('no_response', 'No Response / Expired')], db_index=True, default='identified', max_length=50, verbose_name='Pipeline Status')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=20, verbose_name='Priority')),
                ('first_contact_date', models.DateField(blank=True, null=True, verbose_name='First Contact Date')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='Last Contact Date')),
                ('follow_up_1_date', models.DateField(blank=True, null=True, verbose_name='Follow-up #1 Date')),
                ('follow_up_2_date', models.DateField(blank=True, null=True, verbose_name='Follow-up #2 Date')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Response Date')),
                ('meeting_scheduled', models.CharField(blank=True, help_text='Status or date/time of scheduled meeting', max_length=255, verbose_name='Meeting Scheduled')),
                ('application_submitted', models.CharField(blank=True, help_text='e.g. Yes / No / In Progress', max_length=100, verbose_name='Application Submitted')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('llm_research_summary', models.TextField(blank=True, help_text="AI-generated summary of professor's work, methodology, and key focus areas", verbose_name='LLM Research Summary')),
                ('llm_alignment_hook', models.TextField(blank=True, help_text='AI-synthesized explanation of alignment between candidate background and lab work', verbose_name='LLM Alignment Hook')),
                ('llm_draft_email', models.TextField(blank=True, help_text='AI-generated personalized outreach email draft', verbose_name='LLM Draft Email')),
                ('notes', models.TextField(blank=True, help_text='Action items, reminders, interview notes, or general context', verbose_name='Notes & Next Action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
