# Generated by Django 6.1 on 2026-08-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when changes were last pushed to Google Sheet', null=True, verbose_name='Last Synced to Sheet At'),
        ),
        migrations.AddField(
            model_name='professor',
            name='sheet_row_index',
            field=models.IntegerField(blank=True, db_index=True, help_text='1-based row number in Google Sheet for direct updates', null=True, verbose_name='Sheet Row Index'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='pipeline_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('identified', 'Identified / Backlog'), ('researched', 'Researched / Qualified'), ('email_drafted', 'Email Drafted'), ('contacted', 'First Contact Sent'), ('follow_up_1', 'Follow-up #1 Sent'), ('follow_up_2', 'Follow-up #2 Sent'), ('discussion', 'In Discussion / Replied'), ('meeting_scheduled', 'Meeting Scheduled'), ('interviewed', 'Interviewed'), ('applied', 'Application Submitted'), ('accepted', 'Accepted / Offer'), ('declined', 'Declined / Closed'), ('no_response', 'No Response / Expired')], db_index=True, default='pending', max_length=50, verbose_name='Pipeline Status'),
        ),
    ]
