# Generated by Django 6.1 on 2026-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor_last_synced_at_professor_sheet_row_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='pipeline_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('researching', 'Researching'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('applied', 'Applied'), ('identified', 'Identified / Backlog'), ('researched', 'Researched / Qualified'), ('email_drafted', 'Email Drafted'), ('contacted', 'First Contact Sent'), ('follow_up_1', 'Follow-up #1 Sent'), ('follow_up_2', 'Follow-up #2 Sent'), ('discussion', 'In Discussion / Replied'), ('meeting_scheduled', 'Meeting Scheduled'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted / Offer'), ('declined', 'Declined / Closed'), ('no_response', 'No Response / Expired')], db_index=True, default='pending', max_length=50, verbose_name='Pipeline Status'),
        ),
    ]
