# Generated by Django 6.1 on 2026-08-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_professor_pipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='fit_score',
            field=models.IntegerField(blank=True, help_text='AI-calculated alignment score between 1 and 10', null=True, verbose_name='Fit Score (1-10)'),
        ),
    ]
